### ISSUE TITLE
Use a JSON file

### ISSUE THREAD

**Issue by piranna** [Xe/printerfacts#1]
Move the facts to a JSON file instead of being hard-coded for easier management.

**Comment by Xe** [comment]
Given the constraints of the platform it's run on (https://stdlib.com) I didn't want to complicate things with file I/O. Patches would be welcome.

**Comment by piranna** [comment]
JSON files can be loaded by using `require()`, as it's done with other Node.js modules :-)

**Comment by piranna** [comment]
Great! ^^
